# The base go-image
FROM golang:1.14-alpine

RUN su -
RUN mkdir /app3

# Copy all files from the current directory to the app directory
COPY . /app3

# Set working directory
WORKDIR /app3

# Run command as described:
# go build will build an executable file named server in the current directory
#RUN go build hserver.go
RUN go build mux.go
#RUN go build routes.go
# Run the server executable
CMD ["/app3/routes"]
