# The base go-image
FROM alpine:latest
FROM deepatp/golangcentos:base

RUN su -
RUN mkdir /app

# Copy all files from the current directory to the app directory
COPY . /app/

# Set working directory
WORKDIR /app
# Run command as described:
# go build will build an executable file named server in the current directory

ENV AWS_ACCESS_KEY_ID=AKIAWXL533ZHLA7764DX
ENV AWS_SECRET_ACCESS_KEY=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

RUN  go get -u github.com/aws/aws-sdk-go
#RUN go install github.com/aws/aws-sdk-go/...
#RUN go
RUN go build upload1.go
RUN go build upload2.go
# Run the server executable
#CMD [ "/app/upload1" 
