FROM alpine:latest
FROM centos:8

RUN yum -y update
RUN yum install gcc git -y && yum clean all
ENV GO_VERSION 1.17.1
RUN curl -L https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz -o go$GO_VERSION.linux-amd64.tar.gz && tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz && rm -f go$GO_VERSION.linux-amd64.tar.gz
ENV PATH /usr/local/go/bin:$PATH
ENV GOROOT /usr/local/go
RUN go env -w GOPROXY="https://goproxy.cn,direct"
RUN \cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN  go get -u github.com/aws/aws-sdk-go
RUN go get github.com/gin-gonic/gin
RUN yum update -y
RUN yum install -y python3-pip
RUN pip3 install awscli --upgrade --user
#RUN yum install awscli -y
