# The base go-image
FROM alpine:latest
FROM deepatp/golangcentos:base

RUN su -
RUN mkdir /app

# Copy all files from the current directory to the app directory
COPY . /app

# Set working directory
WORKDIR /app
# Run command as described:
# go build will build an executable file named server in the current directory

RUN  go get -u github.com/aws/aws-sdk-go
#RUN go install github.com/aws/aws-sdk-go/...
#RUN go
RUN go run main.go golangbucket golang.csv

# Run the server executable
#CMD [ "/app/main" ]
