# The base go-image
FROM alpine:latest
FROM deepatp/golangcentos:base

RUN su -
RUN mkdir /app

#RUN yum install python3 -y
#RUN yum install pip3 awscli -y
# Copy all files from the current directory to the app directory
COPY . /app
ENV AWS_ACCESS_KEY_ID=AKIAWXL533ZHLA7764DX
ENV AWS_SECRET_ACCESS_KEY=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

# Set working directory
WORKDIR /app
# Run command as described:
# go build will build an executable file named server in the current directory

RUN  go get -u github.com/aws/aws-sdk-go
#RUN go install github.com/aws/aws-sdk-go/...
#RUN go
RUN go build main.go
RUN sh check.sh
#ENTRYPOINT ./main golangbucket golang.csv
RUN ./main golangbucket golang.csv
CMD ls -l
# Run the server executable
#CMD [ "/app/main" ]
